server:
  port: 8082
  servlet:
    context-path: /api
spring:
  ai:
    openai:
      api-key: sk-0adebfae724a4d9aadb6214660b19879
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://triflingmat.icu/shop_project
    username: shop_project
    password: PaPBZ84DFkdNFnMR
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
