server:
  port: 8082
  servlet:
    context-path: /api
spring:
  ai:
    openai:
      api-key: apikey
      base-url: AI-url
      chat:
        options:
          model: AI-model

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost.icu/shop_project
    username: shop_project
    password: password
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
